
#

asm_diskgroups:
 - diskgroup: crs
   state: present
   redundancy: normal
   attributes:
     - {name: au_size, value: 1m}
     - {name: compatible.asm, value: 12.2.0.1.0}
     - {name: compatible.rdbms, value: 12.2.0.1.0}
   disk:
     - {device: /dev/sdc, asmlabel: crs01, asmdevice: 'ORCL:CRS01'}
     - {device: /dev/sdd, asmlabel: crs02, asmdevice: 'ORCL:CRS02'}
     - {device: /dev/sde, asmlabel: crs03, asmdevice: 'ORCL:CRS03'}
 - diskgroup: data
   state: present
   redundancy: external
   attributes:
     - {name: au_size, value: 4M}
     - {name: compatible.asm, value: 12.2.0.1.0}
     - {name: compatible.rdbms, value: 12.2.0.1.0}
   disk:
     - {device: /dev/sdf, asmlabel: data01, asmdevice: 'ORCL:DATA01'}
     - {device: /dev/sdg, asmlabel: data02, asmdevice: 'ORCL:DATA02'}
     - {device: /dev/sdh, asmlabel: data03, asmdevice: 'ORCL:DATA03'}
 - diskgroup: fra
   state: present
   redundancy: external
   attributes:
     - {name: au_size, value: 4M}
     - {name: compatible.asm, value: 12.2.0.1.0}
     - {name: compatible.rdbms, value: 12.2.0.1.0}
   disk:
     - {device: /dev/sdi, asmlabel: fra01, asmdevice: 'ORCL:FRA01'}
     - {device: /dev/sdj, asmlabel: fra02, asmdevice: 'ORCL:FRA02'}
     - {device: /dev/sdk, asmlabel: fra03, asmdevice: 'ORCL:FRA03'}
 - diskgroup: appdg1
   state: present
   redundancy: external
   attributes:
     - {name: au_size, value: 4M}
     - {name: compatible.asm, value: 12.2.0.1.0}
     - {name: compatible.rdbms, value: 12.2.0.1.0}
   disk:
     - {device: /dev/sdl, asmlabel: appdg01, asmdevice: 'ORCL:APPDG01'}
     - {device: /dev/sdm, asmlabel: appdg02, asmdevice: 'ORCL:APPDG02'}
     - {device: /dev/sdn, asmlabel: appdg03, asmdevice: 'ORCL:APPDG03'}
