- basename_vm: db
  num_vm: 1
  hostgroup: dbdemo
  domain: demo.lab
  box: oravirt/ol74
  vagrant_user: vagrant
  vagrant_pass: vagrant
  ram: 3200
  cpu: 1
  base_pub_ip: 192.168.9.230
  synced_folders:
     - {src: /Users/miksan/Downloads/oracle, dest: /media/swrepo}
  base_disk_path:
  create_local_disk: true
  local_disks:
     - {name: u01, size: 75, count: 1}
     - {name: crs, size: 8, count: 3}
     - {name: data, size: 10, count: 3}
     - {name: fra, size: 20, count: 3}
     - {name: newdg, size: 5, count: 3}
  create_shared_disk: false
  provisioning:
  provisioning_env_override: false

- basename_vm: jenkins
  num_vm: 1
  hostgroup: jenkins
  domain: demo.lab
  box: oravirt/centos73
  vagrant_user: vagrant
  vagrant_pass: vagrant
  ram: 1024
  cpu: 1
  base_pub_ip: 192.168.9.220
  synced_folders:
     - {src: /Users/miksan/Downloads/oracle, dest: /media/swrepo}
  create_local_disk: false
  create_shared_disk: false
  provisioning:
  provisioning_env_override: false

- basename_vm: bitbucket
  num_vm: 1
  hostgroup: bitbucket
  domain: demo.lab
  box: oravirt/centos73
  vagrant_user: vagrant
  vagrant_pass: vagrant
  ram: 1500
  cpu: 1
  base_pub_ip: 192.168.9.210
  synced_folders:
     - {src: /Users/miksan/Downloads/oracle, dest: /media/swrepo}
  create_local_disk: false
